name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetches all history for all tags and branches

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # Use the same Node.js version as your local setup

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Adjust this to where your build output is located